name: Build

# Trigger the workflow on push or pull request
on:
  push:

jobs:
  witness:
    strategy:
      matrix:
        system:
          - witness
          - vigilant
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Setup build dependencies
      run: |
        nix-env -i jq cachix -f '<nixpkgs>'
    - name: Add binary caches
      run: |
        cachix use busc-env
      env:
        CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_SIGNING_KEY }}'        
    - name: Build
      run: |
        nix build .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel
    - name: Cache
      run: |
        nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)' | cachix push busc-env
      env:
        CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_SIGNING_KEY }}'        
